[package]
name = "walletkit"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "lib"]
name = "walletkit"

[dependencies]
bip32 = "0.4.0"
sui_keys = { git = "https://github.com/mystenlabs/sui", package = "sui-keys" }
sui_types = { git = "https://github.com/mystenlabs/sui", package = "sui-types" }
# tokio = { version = "1.47.1", features = ["full"] }
uniffi = "0.30"

[build-dependencies]
uniffi = { version = "0.30", features = ["build"] }

[profile.release]
opt-level = "z" # Optimize for size (even more than "s")
lto = true # Enable Link-Time Optimization
strip = "symbols" # Strip debug symbols from the binary
codegen-units = 1 # Reduce the number of codegen units to increase LTO effectiveness
panic = "abort" # Abort on panic to remove stack unwinding machinery